version: 2.1

orbs:
  node: circleci/node@4.2.0

workflows:
  test_smart_contracts:
    jobs:
      - test:
          context: Local  

jobs:
  test:
    executor: node/default
    docker:
      - image: circleci/node:12
      - image: trufflesuite/ganache-cli
        command: ganache-cli -i 1234 -e 100000000000 -l 4700038 -d
    steps:
      - checkout
      - run:
          name: "echo an env var that is part of our context"
          command: |
            echo $ETH_FACTORY_ADDRESS
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: 
          name: Run all tests
          command: npm test

