version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: trufflesuite/ganache-cli
        command: ganache-cli -i 1234 -e 100000000000 -l 4700038
    steps:
      - run: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
        - build
        - test